main: com.williambl.plugins.testplugin.testPlugin
name: TestPlugin
version: 1.0
author: Willbl3pic
description: Shows a message when a player places a block.
commands:
    test:
        description: A test command.
        usage: /<command>